version: '3'

services:
  brag-sheet-api:
    container_name: brag-sheet-api
    build:
      context: .
    ports:
      - '8080:8080'
    environment:
      HOST: bragdb
      USERNAME: doadmin
      PASSWORD: sekret
      PORT:     5432
      DATABASE: defaultdb
      SSLMODE:  disable
    depends_on:
      - bragdb
  bragdb:
    container_name: bragdb
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: sekret
      POSTGRES_USER: doadmin
      POSTGRES_DB: defaultdb

